/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_wasmemulator_free: (a: number, b: number) => void;
export const wasmemulator_af: (a: number) => number;
export const wasmemulator_battery_ram: (a: number) => [number, number];
export const wasmemulator_bc: (a: number) => number;
export const wasmemulator_de: (a: number) => number;
export const wasmemulator_flag_carry: (a: number) => number;
export const wasmemulator_flag_half_carry: (a: number) => number;
export const wasmemulator_flag_subtract: (a: number) => number;
export const wasmemulator_flag_zero: (a: number) => number;
export const wasmemulator_framebuffer_rgba: (a: number) => [number, number];
export const wasmemulator_hl: (a: number) => number;
export const wasmemulator_ime: (a: number) => number;
export const wasmemulator_is_halted: (a: number) => number;
export const wasmemulator_load_battery_ram: (a: number, b: number, c: number) => void;
export const wasmemulator_load_demo: (a: number) => void;
export const wasmemulator_load_rom: (a: number, b: number, c: number) => void;
export const wasmemulator_new: () => number;
export const wasmemulator_pc: (a: number) => number;
export const wasmemulator_press_button: (a: number, b: number) => void;
export const wasmemulator_read_byte: (a: number, b: number) => number;
export const wasmemulator_reg_a: (a: number) => number;
export const wasmemulator_reg_b: (a: number) => number;
export const wasmemulator_reg_c: (a: number) => number;
export const wasmemulator_reg_d: (a: number) => number;
export const wasmemulator_reg_e: (a: number) => number;
export const wasmemulator_reg_f: (a: number) => number;
export const wasmemulator_reg_h: (a: number) => number;
export const wasmemulator_reg_l: (a: number) => number;
export const wasmemulator_release_button: (a: number, b: number) => void;
export const wasmemulator_sp: (a: number) => number;
export const wasmemulator_step_frame: (a: number) => void;
export const wasmemulator_total_cycles: (a: number) => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_start: () => void;
